// build_report.js -- generates docs/Big_Data_Hadoop_Taxi_Analytics_Report.docx
const fs = require('fs'), path = require('path');
const L = require('./build_report_lib.js');
const {d, D, P, RP, H1, H2, H3, bullet, bulletRich, code, caption, table, tocLine, figure,
       pyfile, evidence, grepEvidence, pb, n, usd, pct, mb, gb, B} = L;
const {Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel, LevelFormat,
       TableOfContents, Header, Footer, PageNumber} = d;

const C = D.clean;
const RAW = C.INPUT_RECORDS, VALID = C.VALID_RECORDS;
const jobs = D.jobs.filter(j => j.name);
const byLog = Object.fromEntries(D.jobs.map(j => [j.log, j]));
const cleanJob = byLog['10_job_clean'];
const revJob = byLog['14_job_revenue'];
const routeJob = byLog['17_job_routes'];
const benchJob = byLog['25_job_revenue_bench'];
const tinyJob = byLog['26_bench_hadoop_tiny'];
const halfJob = byLog['27_bench_hadoop_half'];
const stage2 = jobs.filter(j => /^1[1-5]-/.test(j.name));
const pipelineJobs = jobs.filter(j => !/^BENCH/.test(j.name));

const rejected = RAW - VALID;
const rej = k => C[k] || 0;
const rejPct = k => (rej(k) / RAW * 100);
const topZonesShare = D.top10_zones.reduce((a, z) => a + z.trips, 0) / VALID * 100;
const routeCombIn = routeJob.comb_in || 0, routeCombOut = routeJob.comb_out || 0;

// ---------------------------------------------------------------- title page
const title = [
  new Paragraph({spacing: {before: 2200, after: 0}, alignment: AlignmentType.CENTER,
    children: [new TextRun({text: 'Distributed Taxi Trip Analytics', size: 48, bold: true,
                            color: L.HEAD, font: 'Calibri'})]}),
  new Paragraph({spacing: {before: 120, after: 500}, alignment: AlignmentType.CENTER,
    children: [new TextRun({text: 'Using Apache Hadoop, HDFS and Python MapReduce',
                            size: 28, color: L.HEAD, font: 'Calibri'})]}),
  new Paragraph({spacing: {after: 90}, alignment: AlignmentType.CENTER,
    children: [new TextRun({text: 'Big Data Essentials — Individual Practical Case Study',
                            size: 22, color: L.MUTED, font: 'Calibri'})]}),
  new Paragraph({spacing: {after: 600}, alignment: AlignmentType.CENTER,
    children: [new TextRun({text: 'NYC Taxi & Limousine Commission Yellow Taxi Trip Records, January–March 2026',
                            size: 22, color: L.MUTED, font: 'Calibri'})]}),
  table(['', ''], [
    ['Records processed', n(RAW) + ' raw trips'],
    ['Records analysed', n(VALID) + ' after cleaning'],
    ['Raw dataset size', '1.10 GB CSV (converted from 182 MB of Parquet)'],
    ['Platform', 'Apache Hadoop 3.5.0, pseudo-distributed, OpenJDK 21'],
    ['Processing model', 'Hadoop Streaming with Python 3.11 mappers and reducers'],
    ['MapReduce jobs executed', pipelineJobs.length + ' pipeline + ' + (jobs.length - pipelineJobs.length) + ' benchmark (all succeeded)'],
    ['Total cluster time', n(jobs.reduce((a, j) => a + (j.elapsed || 0), 0)) + ' seconds across ' + jobs.length + ' YARN applications'],
  ], [30, 70], {size: 18, noHeader: true}),
  new Paragraph({spacing: {before: 700}, alignment: AlignmentType.CENTER,
    children: [new TextRun({text: 'Every figure in this report is the output of a MapReduce job that actually ran.',
                            size: 19, italics: true, color: L.MUTED, font: 'Calibri'})]}),
  new Paragraph({spacing: {after: 0}, alignment: AlignmentType.CENTER,
    children: [new TextRun({text: 'Job logs, Hadoop counters and YARN application records are in evidence/.',
                            size: 19, italics: true, color: L.MUTED, font: 'Calibri'})]}),
  pb(),
];

const TOC_ENTRIES = [
  ['1. Introduction', 3], ['2. Business Problem', 3], ['3. Dataset Description', 4],
  ['4. Hadoop Environment', 5], ['5. HDFS Design', 7], ['6. Data Cleaning', 8],
  ['7. MapReduce Design', 10], ['8. Mapper and Reducer Implementation', 12],
  ['9. Analytical Results', 14], ['10. Multi-Stage MapReduce', 22], ['11. YARN Analysis', 24],
  ['12. Performance Comparison', 26], ['13. Business Insights', 27], ['14. Limitations', 29],
  ['15. Conclusion', 29], ['16. References', 30],
];
const toc = [
  H1('Table of Contents'),
  ...TOC_ENTRIES.map(([t, pg]) => tocLine(t, pg)),
  new Paragraph({spacing: {before: 300, after: 0},
    children: [new TextRun({text: 'Figures 9.1–9.7 appear in Section 9; code listings in Sections 3, 6, 8 and 10; ' +
      'cluster, HDFS and YARN evidence extracts in Sections 4, 5, 10 and 11.',
      size: 17, italics: true, color: L.MUTED, font: 'Calibri'})]}),
  pb(),
];

// ================================================================ 1. INTRO
const s1 = [
  H1('1. Introduction'),
  P('This report documents the design, implementation and execution of a Hadoop-based analytics solution for New York City yellow-taxi trip records. The work was carried out on a live single-node pseudo-distributed Apache Hadoop 3.5.0 cluster: HDFS stores the dataset, YARN schedules the work, and Hadoop Streaming runs Python mapper and reducer programs across the cluster.'),
  RP([['The dataset comprises three consecutive monthly releases from the NYC Taxi & Limousine Commission — January, February and March 2026 — totalling ', {}],
      [n(RAW) + ' trip records', {bold: true}],
      [' and 1.10 GB of line-oriented CSV. This satisfies the assignment requirement of two-to-three monthly datasets and comfortably exceeds the five-million-record threshold.', {}]]),
  P(pipelineJobs.length + ' MapReduce jobs make up the pipeline: one two-phase cleaning job, nine analytical jobs covering the required analyses, and five Top-N jobs forming the multi-stage workflow. A further ' + (jobs.length - pipelineJobs.length) + ' benchmark jobs were run for the performance comparison in Section 12, giving ' + jobs.length + ' YARN applications in total. All completed with exit status zero. Their application identifiers, counters and elapsed times appear throughout this report and in full in the evidence directory.'),
  H2('1.1 What this report argues'),
  P('Three findings run through the analysis and are worth stating at the outset, because each one shaped a decision in the implementation.'),
  bulletRich([['Demand is remarkably flat across the working day and concentrated in a very small part of the city. ', {bold: true}],
    ['The busiest hour (' + D.hour_peak[0] + ':00, ' + n(D.hour_peak[1]) + ' trips) carries only ' + (D.hour_peak[1] / D.hour_low[1]).toFixed(1) + ' times the volume of the quietest (' + D.hour_low[0] + ':00), and there is no sharp morning commuter spike at all. Meanwhile the top ten pickup zones out of ' + D.n_zones + ' account for ' + pct(topZonesShare, 1) + ' of all trips.']]),
  bulletRich([['The most frequent routes are not the most profitable ones. ', {bold: true}],
    ['Only ' + D.routes_overlap.length + ' of the top 20 routes by trip count also appear in the top 20 by revenue. Short intra-Manhattan hops dominate volume; airport runs dominate money. This distinction is invisible in a trip-count analysis and is the single most actionable result in the report.']]),
  bulletRich([['At this scale, on this hardware, Pandas beats Hadoop by a factor of ' + (benchJob.elapsed / 10.96).toFixed(0) + '. ', {bold: true}],
    ['That is the honest measured result, and Section 12 explains precisely why it is the expected one, where the crossover lies, and what Hadoop is actually buying.']]),
  H2('1.2 Learning objectives addressed'),
  table(['Objective', 'Where it is demonstrated'], [
    ['Load and organise a large dataset in HDFS', 'Section 5 — directory design, block layout, fsck and dfsadmin evidence'],
    ['Implement Python mapper and reducer programs', 'Sections 7 and 8 — 22 programs, key-value design explained'],
    ['Execute Hadoop Streaming MapReduce jobs', 'Section 9 — all nine analyses, with counters'],
    ['Understand the Shuffle and Sort stage', 'Section 7.2 — and the measured combiner effect in 7.4'],
    ['Perform multi-stage MapReduce processing', 'Section 10 — five stage-2 jobs consuming stage-1 HDFS output'],
    ['Use YARN to monitor MapReduce applications', 'Section 11 — application states, containers, resource usage'],
    ['Analyse and interpret large-scale results', 'Sections 9 and 13'],
    ['Compare conventional processing with Hadoop', 'Section 12 — a three-point scaling benchmark'],
  ], [40, 60]),
];

// ============================================================ 2. BUSINESS PROBLEM
const s2 = [
  H1('2. Business Problem'),
  P('The company is a transportation analytics provider. Its clients — fleet operators, city regulators and mobility planners — need answers to operational questions that are simple to state and expensive to compute: when is demand highest, where does revenue actually come from, which routes are worth positioning vehicles for, how do customers pay, and how much of the data can be trusted at all.'),
  P('The volume is what makes this a big-data problem rather than a spreadsheet problem. A single month of yellow-taxi records is roughly 3.7 million rows; a quarter is over eleven million; a full year approaches forty-five million, and the equivalent green-taxi and for-hire-vehicle feeds multiply that several times over. Any method that requires the whole dataset to sit in one machine’s memory has a hard ceiling, and that ceiling is measured explicitly in Section 12.'),
  H2('2.1 The analytical questions'),
  P('The nine required analyses map onto the business questions as follows. Each one becomes a separate MapReduce job, and the mapping from question to key design is the substance of Section 7.'),
  table(['#', 'Analysis', 'Business question it answers'], [
    ['a', 'Hourly demand', 'When should vehicles be on the road?'],
    ['b', 'Daily demand', 'How does staffing differ between weekdays and weekends?'],
    ['c', 'Pickup locations', 'Where should idle vehicles wait?'],
    ['d', 'Revenue by zone', 'Which neighbourhoods generate the money, not just the trips?'],
    ['e', 'Payment behaviour', 'What is the revenue mix, and where do tips come from?'],
    ['f', 'Distance bands', 'How does pricing behave across trip lengths?'],
    ['g', 'Routes', 'Which origin–destination pairs are worth targeting?'],
    ['h', 'Trip duration', 'How does time-in-traffic affect economics?'],
    ['i', 'Anomalies', 'How much of the feed is unreliable, and in what way?'],
  ], [6, 26, 68]),
  H2('2.2 Why HDFS and MapReduce'),
  P('HDFS provides the storage half of the answer. It splits each file into fixed-size blocks distributed across the cluster, replicates them for fault tolerance, and exposes the whole thing as one namespace. Crucially it also exposes where each block lives, which is what allows the computation to be sent to the data instead of the data to the computation.'),
  P('MapReduce provides the processing half. Its restriction — a map function that sees one record at a time and a reduce function that sees one key’s values at a time, with no shared state — is exactly what makes it parallelisable without coordination. The programmer never writes a lock, a thread or a partition; they choose what the key is, and the framework’s Shuffle-and-Sort stage does the grouping.'),
];

// ============================================================ 3. DATASET
const s3 = [
  H1('3. Dataset Description'),
  P('Source: the official NYC Taxi & Limousine Commission Trip Record Data portal, https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page. Three consecutive monthly Yellow Taxi files were used, together with the official Taxi Zone lookup table that maps the numeric LocationID values to zone and borough names.'),
  table(['File', 'Format', 'Size on disk', 'Records'], [
    ['yellow_tripdata_2026-01.parquet', 'Parquet', '61.2 MB', n(3724889)],
    ['yellow_tripdata_2026-02.parquet', 'Parquet', '56.0 MB', n(3399866)],
    ['yellow_tripdata_2026-03.parquet', 'Parquet', '64.7 MB', n(3952451)],
    ['Total (Parquet)', '—', '182.0 MB', n(RAW)],
    ['Total (converted CSV)', 'CSV', '1.10 GB', n(RAW)],
  ], [42, 14, 20, 24], {right: [2, 3]}),
  caption('Table 3.1 — Source files. The 6.2x expansion from Parquet to CSV is the price of a line-oriented format, and is discussed below.'),
  H2('3.1 Schema'),
  P('Each record has twenty fields. The columns that carry the analysis are marked.'),
  table(['#', 'Field', 'Type', 'Used for'], [
    ['0', 'VendorID', 'int32', '—'],
    ['1', 'tpep_pickup_datetime', 'timestamp', 'Analyses a, b, h — and duration is derived from 1 and 2'],
    ['2', 'tpep_dropoff_datetime', 'timestamp', 'Analyses h, i'],
    ['3', 'passenger_count', 'int64', 'Flagged in cleaning; see Section 6.3'],
    ['4', 'trip_distance', 'double', 'Analyses f, i'],
    ['5', 'RatecodeID', 'int64', '—'],
    ['6', 'store_and_fwd_flag', 'string', '—'],
    ['7', 'PULocationID', 'int32', 'Analyses c, d, g'],
    ['8', 'DOLocationID', 'int32', 'Analysis g'],
    ['9', 'payment_type', 'int64', 'Analysis e'],
    ['10', 'fare_amount', 'double', 'Analyses d, e, f, h, i'],
    ['11–15', 'extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge', 'double', 'tip_amount feeds analyses d and e'],
    ['16', 'total_amount', 'double', 'Analyses d, e, f, g, h'],
    ['17–19', 'congestion_surcharge, Airport_fee, cbd_congestion_fee', 'double', '—'],
  ], [7, 34, 14, 45]),
  H2('3.2 Parquet for storage, CSV for streaming'),
  P('The TLC publishes Parquet. Parquet is columnar and compressed: a query that touches three of twenty columns reads only those three columns’ pages, and the three months occupy 182 MB rather than 1.1 GB. For archival storage and for engines that understand it, Parquet is unambiguously the right format.'),
  RP([['It is nevertheless the wrong format for this assignment, for a specific mechanical reason. A Hadoop Streaming mapper is a plain process that reads ', {}],
      ['one text line at a time from standard input', {italics: true}],
      ['. Parquet is not line-oriented; it is a block-structured binary format with a footer, and a byte offset into a Parquet file is not the start of anything. Feeding it to a streaming mapper would require a custom InputFormat written in Java — which would defeat the purpose of using Python.', {}]]),
  P('The conversion is therefore a deliberate, documented trade: 6.2 times more bytes on disk in exchange for a format that HDFS can split at any newline and that a Python process can read with a for-loop. In production the correct answer would be to keep Parquet and use an engine that reads it natively; the CSV here exists to demonstrate line-oriented Hadoop Streaming, which is what the assignment is teaching.'),
  pyfile('scripts/parquet_to_csv.py', {from: 27, to: 47}),
  caption('Listing 3.1 — scripts/parquet_to_csv.py (conversion loop). Batched at 200,000 rows so the converter’s own memory stays bounded; timestamps are normalised to a fixed format string so the mappers can parse them cheaply.'),
];

// ============================================================ 4. HADOOP ENV
const s4 = [
  H1('4. Hadoop Environment'),
  table(['Component', 'Configuration'], [
    ['Apache Hadoop', '3.5.0 (binary distribution)'],
    ['Java', 'OpenJDK 21'],
    ['Python', '3.11 — all mappers and reducers, via Hadoop Streaming'],
    ['Cluster mode', 'Pseudo-distributed, single node'],
    ['Daemons', 'NameNode, DataNode, SecondaryNameNode, ResourceManager, NodeManager, JobHistoryServer'],
    ['Host resources', '2 vCPU, 8 GB RAM, Linux x86-64'],
    ['HDFS replication', '1 (single DataNode)'],
    ['HDFS block size', '128 MB'],
    ['YARN NodeManager', '5,120 MB memory, 4 vcores'],
    ['Container sizing', 'map 1,024 MB, reduce 1,024 MB, ApplicationMaster 1,024 MB'],
    ['Streaming JAR', 'share/hadoop/tools/lib/hadoop-streaming-3.5.0.jar'],
  ], [26, 74]),
  H2('4.1 Services running'),
  P('The six daemons below are the cluster. Three belong to HDFS (storage), two to YARN (resource management) and one to MapReduce (job history).'),
  evidence('evidence/E1_services_running.txt', 1, 10),
  caption('Evidence 4.1 — jps output. The NodeManager process id is higher than the others because it was restarted mid-session; Section 4.3 explains why.'),
  P('Note that no mapper or reducer in this project imports a third-party Python library. They use only the standard library, so they run unchanged on any cluster node without a provisioning step — which is the practical reason Hadoop Streaming is worth using at all.'),
  H2('4.2 Cluster capacity'),
  grepEvidence('evidence/E3_hdfs_data_and_blocks.txt',
    ['Configured Capacity:', 'Present Capacity:', 'DFS Remaining:', 'DFS Used:', 'Live datanodes',
     'Name: 127.0.0.1', 'Decommission Status', 'Missing blocks', 'Under replicated'], 11),
  caption('Evidence 4.2 — hdfs dfsadmin -report (extract). One live DataNode, no missing or under-replicated blocks.'),
  H2('4.3 Two documented deviations from a textbook install'),
  P('Both are properties of the execution environment rather than of Hadoop, and both are recorded here rather than hidden, because either one would otherwise look like a defect in the work.'),
  H3('Daemons started individually rather than via start-dfs.sh'),
  RP([['The conventional scripts ', {}], ['start-dfs.sh', {code: true}], [' and ', {}], ['start-yarn.sh', {code: true}],
      [' launch each daemon over SSH, even in pseudo-distributed mode where the target host is localhost. This container has no ', {}],
      ['sshd', {code: true}], [', so each daemon was started directly with ', {}],
      ['hdfs --daemon start <role>', {code: true}], [' and ', {}], ['yarn --daemon start <role>', {code: true}],
      ['. The resulting cluster is identical — the same JVMs with the same configuration — only the launch mechanism differs.', {}]]),
  H3('The YARN disk-health threshold was raised'),
  P('Mid-way through the first full run the NodeManager began flapping between healthy and unhealthy, and the cleaning job stalled at 69% and was retried by the ApplicationMaster. The cause was not a Hadoop fault:'),
  code(['Disk(s) failed: 1/1 local-dirs usable space is below configured utilization',
        'percentage/no more usable space [ /home/claude/hadoop_data/tmp/nm-local-dir :',
        'used space above threshold of 90.0% ]'], {size: 14}),
  RP([['The host presents a 252 GB device of which only about 26 GB is writable. YARN computes utilisation from the device’s total and usable space, so it read the node as 90% full and marked it ', {}],
      ['UNHEALTHY', {code: true}], [', which withdraws all containers. The fix was to raise ', {}],
      ['yarn.nodemanager.disk-health-checker.max-disk-utilization-per-disk-percentage', {code: true}],
      [' to 99 and set an absolute floor of 2,048 MB free instead. After the change the node stayed ', {}],
      ['RUNNING', {code: true}], [' for every job that followed.', {}]]),
  P('This is worth recording for a second reason: it is a realistic example of the operational failure mode that dominates real Hadoop work. The job did not fail because the code was wrong; it failed because a resource-manager health check disagreed with the storage layer, and diagnosing it meant reading NodeManager logs rather than job logs.'),
  P('Finally, the Hadoop native libraries are not present in this build, so every job logs "Unable to load native-hadoop library for your platform". Java implementations of checksumming and compression are used instead. This is a performance note, not an error, and it slightly penalises the Hadoop side of the Section 12 benchmark.'),
];

// ============================================================ 5. HDFS DESIGN
const s5 = [
  H1('5. HDFS Design'),
  P('The directory layout separates data by lifecycle stage rather than by analysis. Raw data is never modified; the cleaned dataset is written once and is the input to every analytical job; each job writes to its own output directory; and the archive holds the reference lookup table and a dated copy of the stage-1 revenue result.'),
  evidence('evidence/E2_hdfs_structure.txt', 1, 21),
  caption('Evidence 5.1 — hdfs dfs -ls -R /taxi_project'),
  H2('5.1 Why the output directories are created and then deleted'),
  RP([['The assignment asks for the output directories to be created up front, and they are. They are then removed again before the jobs are submitted, because MapReduce ', {}],
      ['refuses to write into a directory that already exists', {italics: true}],
      [' and fails the job with ', {}], ['FileAlreadyExistsException', {code: true}],
      ['. This is deliberate framework behaviour, not an inconvenience: a job that silently overwrote a previous result would make a long pipeline impossible to reason about, since a partially-overwritten directory is indistinguishable from a complete one. Each job therefore creates its own output directory as its first act.', {}]]),
  H2('5.2 Loading the data and the resulting block layout'),
  grepEvidence('evidence/E3_hdfs_data_and_blocks.txt',
    ['yellow_tripdata_2026-01.csv', 'yellow_tripdata_2026-02.csv', 'yellow_tripdata_2026-03.csv',
     '/taxi_project/input/cleaned/part-', 'Total size:', 'Total files:', 'Total blocks (validated)',
     'Status:', 'Average block'], 15),
  caption('Evidence 5.2 — file sizes and fsck block report for the raw input.'),
  P('The block layout is the single most important thing to understand about the whole exercise, because it determines the parallelism of every job that follows. With a 128 MB block size, the three raw CSV files occupy ten blocks. Hadoop creates one map task per input split, and by default a split is a block — so the cleaning job launched map tasks one per block, and on a cluster with ten free containers they could all have run simultaneously.'),
  RP([['That is the entire mechanism by which Hadoop scales. The file is not read by one process that then distributes work; the file is ', {}],
      ['already', {italics: true}],
      [' physically divided, and each map task reads only its own block — ideally from the local disk of the node it runs on. Doubling the data doubles the number of blocks and therefore the number of map tasks, and on a wide enough cluster the wall-clock time does not change.', {}]]),
  P('One subtlety: a 128 MB block boundary will almost always fall in the middle of a CSV line. Hadoop’s TextInputFormat handles this by having each split skip its first partial line and read past its own end to finish the last one, so no record is lost or double-counted. This is why the mappers can assume they receive whole lines, and why the record counts in Section 6 reconcile exactly.'),
  H2('5.3 Storage footprint'),
  table(['Path', 'Contents', 'Size'], [
    ['/taxi_project/input/raw', '3 monthly CSV files, ' + n(RAW) + ' records', '1.10 GB'],
    ['/taxi_project/input/cleaned', '2 part files, ' + n(VALID) + ' records', '1.03 GB'],
    ['/taxi_project/output/*', '14 job result directories', 'under 5 MB total'],
    ['/taxi_project/archive', 'Zone lookup and a dated copy of the stage-1 revenue result', 'under 1 MB'],
  ], [34, 46, 20], {right: [2]}),
  P('The asymmetry is worth noting. Over a gigabyte of input produces a few megabytes of output, because every analysis here is an aggregation: eleven million records collapse to 24 hours, 7 days, ' + D.n_zones + ' zones or ' + n(D.n_routes) + ' routes. That ratio is the reason the reduce phase is cheap and the map phase is not, and it is why combiners matter so much (Section 7.4).'),
];

// ============================================================ 6. DATA CLEANING
const s6 = [
  H1('6. Data Cleaning'),
  RP([['Cleaning was implemented as a MapReduce job in its own right rather than as a preprocessing script, for two reasons: it has to read the same gigabyte that every other job reads, and duplicate detection across eleven million records is itself a distributed problem. The job is ', {}],
      [cleanJob.app, {code: true}], [', it processed ', {}], [n(RAW), {bold: true}],
      [' records with ' + cleanJob.maps + ' map tasks and ' + cleanJob.reds + ' reduce tasks, and it retained ', {}],
      [n(VALID) + ' (' + pct(VALID / RAW * 100, 2) + ')', {bold: true}], ['.', {}]]),
  H2('6.1 How the job works'),
  P('The mapper validates each record and emits the entire validated record as the key, with a constant value. This is the point of the design: Shuffle-and-Sort brings byte-identical records together on the same reducer, so the reducer can emit each distinct record once and count the extra copies. It is a distributed DISTINCT, expressed purely through the choice of key.'),
  P('Every rejection increments a named Hadoop counter rather than being silently dropped, so the exact number and percentage of each defect is recoverable from the job report — which is what Table 6.1 is built from.'),
  H2('6.2 Results'),
  table(['Rule', 'Records', '% of raw', 'Action'], [
    ['Input records', n(RAW), '100.00%', '—'],
    ['Non-positive trip distance', n(rej('NONPOS_DISTANCE')), pct(rejPct('NONPOS_DISTANCE')), 'Reject'],
    ['Non-positive duration (drop-off at or before pickup)', n(rej('NONPOS_DURATION')), pct(rejPct('NONPOS_DURATION')), 'Reject'],
    ['Negative fare or negative total', n(rej('NEG_FARE')), pct(rejPct('NEG_FARE')), 'Reject'],
    ['Trip distance over 200 miles', n(rej('LONG_DISTANCE')), pct(rejPct('LONG_DISTANCE')), 'Reject'],
    ['Duration over 24 hours', n(rej('LONG_DURATION')), pct(rejPct('LONG_DURATION')), 'Reject'],
    ['Timestamp outside the study window', n(rej('OUT_OF_WINDOW')), pct(rejPct('OUT_OF_WINDOW')), 'Reject'],
    ['Fare over $1,000', n(rej('HIGH_FARE')), pct(rejPct('HIGH_FARE')), 'Reject'],
    ['CSV header lines', n(rej('HEADER')), pct(rejPct('HEADER')), 'Reject'],
    ['Total rejected', n(rejected), pct(rejected / RAW * 100), '—'],
    ['Invalid passenger_count', n(rej('PASSENGER_FLAGGED')), pct(rejPct('PASSENGER_FLAGGED')), 'Flag and KEEP'],
    ['Exact duplicate records', n(rej('DUPLICATE_RECORDS')), pct(rej('DUPLICATE_RECORDS') / RAW * 100), 'Deduplicate'],
    ['Records retained for analysis', n(VALID), pct(VALID / RAW * 100), '—'],
  ], [42, 18, 16, 24], {right: [1, 2]}),
  caption('Table 6.1 — Cleaning outcome, taken directly from the job’s CLEANING counter group. A record can fail only one rule: the mapper rejects at the first failure, so the categories are disjoint and sum exactly.'),
  H2('6.3 The passenger_count decision, and why the job was re-run'),
  P('The first version of the cleaning rules rejected any record whose passenger_count was blank, zero or above eight. That rule removed ' + n(rej('PASSENGER_FLAGGED')) + ' records — ' + pct(rejPct('PASSENGER_FLAGGED'), 1) + ' of the entire feed — and it was wrong.'),
  P('passenger_count is entered by the driver, and roughly a quarter of the 2026 feed leaves it blank or zero. More to the point, it is not an input to any of the nine required analyses: not one of them counts passengers. Discarding a quarter of the trips to enforce a field that nothing reads would have biased every demand figure, every revenue total and every route ranking in this report, in an unknown direction — because there is no reason to assume the drivers who skip the field are a random sample.'),
  RP([['The rule was changed to flag-and-keep: the record is retained, the field is normalised to an explicit empty value meaning "unknown", and the counter ', {}],
      ['PASSENGER_FLAGGED', {code: true}], [' records how many. The cleaning job was re-run from scratch, and the retained population went from ', {}],
      ['7,670,701 to ' + n(VALID), {bold: true}], ['. Every figure in this report comes from the second run.', {}]]),
  P('The general principle, which the assignment states as "do not simply delete unusual records without justification", is that a cleaning rule must be justified by the analysis it protects. A non-positive distance genuinely breaks the distance-band and fare-per-mile analyses; a negative fare genuinely corrupts a revenue sum; a drop-off before its pickup genuinely breaks a duration calculation. A blank passenger count breaks nothing here.'),
  H2('6.4 Duplicates'),
  RP([['The deduplication phase found ', {}], [n(rej('DUPLICATE_RECORDS')) + ' exact duplicates', {bold: true}],
      [' — the reducer’s DISTINCT_RECORDS counter (' + n(C.DISTINCT_RECORDS) + ') equals the mapper’s VALID_RECORDS counter exactly. That is a genuine finding rather than a broken test: a duplicate requires all twenty fields to match, including two second-resolution timestamps and four monetary amounts, so the TLC’s own de-duplication is evidently effective. The check cost a full gigabyte of shuffle, which is why the cleaning job took ' + cleanJob.elapsed + ' seconds against roughly 190 seconds for the analytical jobs that follow it.', {}]]),
  H2('6.5 Cleaning mapper'),
  pyfile('mappers/mapper_clean.py', {from: 47, to: 100}),
  caption('Listing 6.1 — mappers/mapper_clean.py (validation body, abridged; the complete program is in mappers/). Each rejection increments a counter via the reporter:counter: protocol on stderr, which is how a Streaming program talks to the Hadoop framework.'),
];

// ============================================================ 7. MAPREDUCE DESIGN
const s7 = [
  H1('7. MapReduce Design'),
  P('In SQL you write a GROUP BY clause. In MapReduce you do not: you choose what the mapper emits as its key, and the framework’s Shuffle-and-Sort stage performs the grouping for you, in parallel, with no shared state and no coordination between tasks. Every analysis in this project is a different answer to one question — what should the key be?'),
  H2('7.1 The key designs'),
  table(['Analysis', 'Map output key', 'Why that key'], [
    ['(a) Hourly', '"14" (hour, zero-padded)', 'Only 24 keys. Padding is mandatory: Hadoop sorts keys as TEXT, so "9" would sort after "23".'],
    ['(b) Daily', '"3_Wednesday_WEEKDAY"', 'An ordinal prefix forces calendar order out of a lexicographic sort; the suffix lets one job answer both the day and the weekday/weekend question.'],
    ['(c) Locations', '"237" (3-digit zone id)', 'One key per zone. Ranking is deliberately not done here — see 7.3.'],
    ['(d) Revenue', '"237" (3-digit zone id)', 'Same grouping, richer value: a numeric vector rather than a count.'],
    ['(e) Payment', '"1_CreditCard"', 'Code plus label, so the output is readable without a join.'],
    ['(f) Distance', '"3_5-10mi"', 'Binning happens in the MAPPER, turning a continuous variable into 5 keys before the shuffle.'],
    ['(g) Routes', '"132->230"', 'A COMPOSITE key — a two-column GROUP BY expressed as string concatenation. This is the whole analysis.'],
    ['(h) Duration', '"4_20-30min"', 'Duration does not exist in the source; it is derived map-side from the two timestamps.'],
    ['(i) Anomalies', 'the anomaly label', 'One record may emit several keys, plus two bookkeeping totals prefixed AAA_/AAB_ so they sort first.'],
    ['Cleaning', 'the ENTIRE record', 'Identical records collide in the shuffle — a distributed DISTINCT.'],
    ['Top-N', 'the constant "TOPN"', 'Deliberately forces one reducer: the only place a GLOBAL ordering can exist.'],
  ], [16, 26, 58]),
  H2('7.2 What Shuffle and Sort actually does'),
  P('Between map and reduce, the framework performs four steps that the programmer never writes:'),
  bulletRich([['Partition. ', {bold: true}], ['Each map output key is hashed and assigned to a reducer — by default hash(key) mod numReduceTasks. All records with the same key therefore land on the same reducer, which is the guarantee the whole model rests on.']]),
  bulletRich([['Sort. ', {bold: true}], ['Each map task sorts its output by key before writing it, spilling to local disk when the sort buffer fills.']]),
  bulletRich([['Copy. ', {bold: true}], ['Each reducer fetches its partition from every map task over HTTP — this is the network-expensive step, and the one a combiner attacks.']]),
  bulletRich([['Merge. ', {bold: true}], ['The reducer merge-sorts the fetched runs so that all values for one key arrive contiguously.']]),
  P('The last point is why every reducer in this project is written as a streaming loop that holds one accumulator and watches for the key to change. It never builds a dictionary of all keys. Memory is constant in the number of groups, which is what lets a single reducer aggregate ' + n(D.n_routes) + ' routes without difficulty.'),
  H2('7.3 Why ranking is not done in the reducer'),
  P('A mapper sees only its own input split; a reducer sees only the keys in its own partition. Neither can know a global ranking. The Top-10 zones and Top-20 routes are therefore computed by a second MapReduce job that reads the first job’s HDFS output — which is exactly the multi-stage workflow of Section 10, and is the honest reason it exists rather than a contrived one.'),
  H2('7.4 The combiner, and the measured effect'),
  P('A combiner is a reducer that Hadoop may run map-side, on one map task’s output, before the shuffle. It is legal only when the aggregation is commutative and associative and when its output has the same shape as its input.'),
  RP([['This is precisely why no mapper in this project emits an average. ', {}],
      ['An average is not associative', {bold: true}],
      [' — the mean of two means is not the mean of the union unless the group sizes are equal. So the mappers emit fixed-length vectors of the form (count, sum, sum, ...) and the reducer divides at the very end. That single decision makes one generic combiner, ', {}],
      ['combiner_sums.py', {code: true}],
      [', legal for five different analyses: revenue, payment, distance, duration and routes.', {}]]),
  P('The effect is measurable in the job counters. For the route analysis — the worst case, with ' + n(D.n_routes) + ' distinct keys:'),
  table(['Counter', 'Value', 'Meaning'], [
    ['Map output records', n(routeJob.map_out), 'One record per trip, emitted by the mappers'],
    ['Combine input records', n(routeCombIn), 'Fed to the map-side combiner'],
    ['Combine output records', n(routeCombOut), 'What actually crossed the shuffle'],
    ['Reduce input records', n(routeJob.red_in), 'Received by the reducers'],
    ['Reduction factor', (routeCombIn / Math.max(routeCombOut, 1)).toFixed(1) + 'x', 'Shuffle traffic avoided'],
  ], [30, 22, 48], {right: [1]}),
  caption('Table 7.1 — Combiner effect on job 08-BusiestPickupDropoffRoutes (' + routeJob.app + ').'),
  P('On a single-node cluster this is the difference between a job that spills to disk repeatedly and one that does not. On a real cluster it is the difference between saturating the network and not.'),
  H2('7.5 Choosing the number of reducers'),
  P('Most jobs here run with one reducer, because after combining, the reduce input is tiny — at most a few tens of thousands of records. The route job uses two, and the cleaning job uses two because its shuffle is a full gigabyte that genuinely benefits from being split. The Top-N jobs must use exactly one: with two reducers there would be two partial rankings and no global answer, which is the trade-off the Top-N pattern makes deliberately.'),
];

// ============================================================ 8. IMPLEMENTATION
const s8 = [
  H1('8. Mapper and Reducer Implementation'),
  P('Twenty-two Python programs were written: eleven mappers, ten reducers and one shared combiner. All of them read standard input and write tab-separated key-value pairs to standard output, which is the entire contract Hadoop Streaming imposes.'),
  table(['Program', 'Role'], [
    ['mappers/mapper_clean.py + reducers/reducer_clean.py', 'Validation and distributed deduplication'],
    ['mappers/mapper_hourly.py + reducers/reducer_hourly.py', '(a) Hourly demand — the reducer is also its own combiner'],
    ['mappers/mapper_daily.py + reducers/reducer_daily.py', '(b) Day-of-week demand'],
    ['mappers/mapper_location.py + reducers/reducer_location.py', '(c) Pickup-zone trip counts'],
    ['mappers/mapper_revenue.py + reducers/reducer_revenue.py', '(d) Revenue by zone — stage 1 of the multi-stage workflow'],
    ['mappers/mapper_payment.py + reducers/reducer_payment.py', '(e) Payment-method behaviour'],
    ['mappers/mapper_distance.py + reducers/reducer_distance.py', '(f) Distance bands'],
    ['mappers/mapper_route.py + reducers/reducer_route.py', '(g) Route aggregation on a composite key'],
    ['mappers/mapper_duration.py + reducers/reducer_duration.py', '(h) Trip-duration bands'],
    ['mappers/mapper_anomaly.py + reducers/reducer_anomaly.py', '(i) Anomaly detection over the raw feed'],
    ['mappers/mapper_topn.py + reducers/reducer_topn.py', 'Generic Top-N — stage 2, reused by five jobs'],
    ['reducers/combiner_sums.py', 'One generic combiner shared by five analyses'],
  ], [46, 54]),
  H2('8.1 A mapper: the route analysis'),
  P('This is the shortest program in the project and the one that best shows the model. The composite key is the entire idea; everything else is arithmetic.'),
  pyfile('mappers/mapper_route.py', {stripDoc: true}),
  caption('Listing 8.1 — mappers/mapper_route.py'),
  H2('8.2 A reducer: streaming aggregation'),
  P('Note what this program does not do: it never accumulates a dictionary keyed by route. Values for one key arrive contiguously, so it holds exactly one accumulator and flushes it when the key changes. That is why one reducer can aggregate ' + n(D.n_routes) + ' routes in constant memory.'),
  pyfile('reducers/reducer_route.py', {stripDoc: true}),
  caption('Listing 8.2 — reducers/reducer_route.py'),
  H2('8.3 The shared combiner'),
  pyfile('reducers/combiner_sums.py', {stripDoc: true}),
  caption('Listing 8.3 — reducers/combiner_sums.py. Element-wise vector addition: commutative, associative, and shape-preserving — the three conditions a combiner must satisfy.'),
  H2('8.4 The anomaly reducer’s sort trick'),
  RP([['The anomaly job needs to express every count as a percentage of the total, but a streaming reducer cannot look ahead. The solution is in the key design: the mapper emits the two bookkeeping totals under the keys ', {}],
      ['AAA_TOTAL_RECORDS', {code: true}], [' and ', {}], ['AAB_ANOMALOUS_RECORDS', {code: true}],
      ['. Because Hadoop sorts keys as text, those two arrive before every real anomaly label, so the denominator is already known when the first label is processed. One pass, no second job, no in-memory table — and it works only with a single reducer, which is why the job is submitted with ', {}],
      ['-D mapreduce.job.reduces=1', {code: true}], ['.', {}]]),
  H2('8.5 Submitting a job'),
  code(['hadoop jar $HADOOP_STREAMING_JAR \\',
        '  -D mapreduce.job.name=08-BusiestPickupDropoffRoutes \\',
        '  -D mapreduce.job.reduces=2 \\',
        '  -input  /taxi_project/input/cleaned \\',
        '  -output /taxi_project/output/routes \\',
        '  -mapper   "python3 mapper_route.py" \\',
        '  -combiner "python3 combiner_sums.py" \\',
        '  -reducer  "python3 reducer_route.py" \\',
        '  -file mappers/mapper_route.py \\',
        '  -file reducers/combiner_sums.py \\',
        '  -file reducers/reducer_route.py'], {size: 15}),
  RP([['The ', {}], ['-file', {code: true}],
      [' arguments matter more than they look. They ship each script into the job’s distributed cache so that every container, on every node, has a local copy before the task starts. Without them the mapper command would only work on nodes where the file happened to exist. This is how a Streaming job stays node-independent — and it is why the mapper command refers to ', {}],
      ['mapper_route.py', {code: true}], [' with no path: the file lands in the container’s working directory.', {}]]),
  H2('8.6 Testing before submitting'),
  P('Every program was tested with a Unix pipeline before it was ever submitted to the cluster, because a MapReduce job takes three minutes to fail and a pipe takes two seconds:'),
  code(['head -200000 yellow_tripdata_2026-01.csv \\',
        '  | python3 mappers/mapper_route.py \\',
        '  | sort \\',
        '  | python3 reducers/combiner_sums.py \\',
        '  | python3 reducers/reducer_route.py'], {size: 15}),
  RP([['The ', {}], ['sort', {code: true}],
      [' is standing in for Shuffle-and-Sort, and that substitution is exact enough to catch essentially every logic error: it reproduces the contiguous-key guarantee that the reducer depends on. What it does not reproduce is partitioning across multiple reducers, which is the one class of bug — assuming a reducer sees all keys — that only appears on the cluster.', {}]]),
];

// ============================================================ 9. RESULTS
const nightTrips = D.hourly.filter(h => ['22','23','00','01','02','03','04','05'].includes(h.hour))
                           .reduce((a, h) => a + h.trips, 0);
const cashRow = D.payment.find(p => p.label === 'Cash');
const flexRow = D.payment.find(p => p.label === 'FlexFare');
const s9 = [
  H1('9. Analytical Results'),
  P('All figures below are computed from the ' + n(VALID) + ' cleaned records. Each subsection names the job that produced it, so any number can be traced to a log file in evidence/.'),
  H2('9.1 (a) Hourly taxi demand'),
  RP([['Job ', {}], ['02-HourlyTaxiDemand', {code: true}], [' · ' + byLog['11_job_hourly'].app + ' · ' + byLog['11_job_hourly'].elapsed + ' s', {}]]),
  figure('01_trips_by_hour.png', 545, 264),
  caption('Figure 9.1 — Trips by hour of pickup.'),
  RP([['Demand peaks at ', {}], [D.hour_peak[0] + ':00 with ' + n(D.hour_peak[1]) + ' trips', {bold: true}],
      [' and bottoms out at ', {}], [D.hour_low[0] + ':00 with ' + n(D.hour_low[1]), {bold: true}],
      [' — a ratio of ' + (D.hour_peak[1] / D.hour_low[1]).toFixed(1) + ' to 1.', {}]]),
  P('Two features of this curve are more interesting than the peak itself.'),
  bulletRich([['There is no morning commuter spike. ', {bold: true}],
    ['The 08:00 hour carries ' + n(D.hourly.find(h => h.hour === '08').trips) + ' trips against ' + n(D.hour_peak[1]) + ' at the evening peak. Yellow taxis are not the morning commute; the subway is. Demand climbs steadily from 05:00 and stays high from 12:00 to 22:00, which is a leisure-and-evening profile, not a rush-hour one.']]),
  bulletRich([['The night is not dead. ', {bold: true}],
    ['The eight hours from 22:00 to 05:00 still carry ' + n(nightTrips) + ' trips, ' + pct(nightTrips / VALID * 100, 1) + ' of the total. Midnight alone (' + n(D.hourly[0].trips) + ') exceeds 06:00 (' + n(D.hourly.find(h => h.hour === '06').trips) + ').']]),
  P('Operationally, the flatness is the finding. A fleet cannot chase a peak that is only ' + (D.hour_peak[1] / D.hour_low[1]).toFixed(1) + ' times the trough across a fourteen-hour plateau; the sensible shift pattern is a long afternoon-to-late-evening block rather than a split morning and evening shift.'),
  H2('9.2 (b) Daily demand and the weekday/weekend split'),
  RP([['Job ', {}], ['03-DailyDemandWeekdayWeekend', {code: true}], [' · ' + byLog['12_job_daily'].app + ' · ' + byLog['12_job_daily'].elapsed + ' s', {}]]),
  figure('02_trips_by_day.png', 520, 313),
  caption('Figure 9.2 — Trips by day of week.'),
  table(['Day', 'Trips', 'Share'], D.daily.map(x =>
    [x.day + (x.kind === 'WEEKEND' ? ' (weekend)' : ''), n(x.trips), pct(x.trips / VALID * 100, 1)]),
    [40, 30, 30], {right: [1, 2]}),
  RP([['Saturday is the busiest day (' + n(D.day_peak.trips) + ') and Monday the quietest (' + n(D.day_low.trips) + '). But the aggregate weekday/weekend comparison is misleading unless it is normalised: weekdays carry ' + n(D.weekday_trips) + ' trips against ' + n(D.weekend_trips) + ' at the weekend, which sounds like weekday dominance until you divide by the number of days. ', {}],
      ['Per day, the weekend average is ' + n(D.weekend_avg) + ' trips against a weekday average of ' + n(D.weekday_avg) + ' — the weekend is ' + pct((D.weekend_avg / D.weekday_avg - 1) * 100, 1) + ' busier, not quieter.', {bold: true}]]),
  P('This is the kind of error that a raw group-by invites and that a per-day rate avoids. The operational reading is that Thursday through Saturday is one continuous high-demand block, and Sunday-to-Monday is the trough where capacity should be pulled back.'),
  H2('9.3 (c) Pickup locations'),
  RP([['Jobs ', {}], ['04-PickupLocationTripCounts', {code: true}], [' and the Top-10/Bottom-10 stage-2 jobs · ' + D.n_zones + ' zones had at least one pickup.', {}]]),
  figure('03_top10_pickup_zones.png', 545, 290),
  caption('Figure 9.3 — Top 10 pickup zones by trip count.'),
  table(['#', 'Zone', 'Trips', '% of all'], D.top10_zones.map(z =>
    [z.rank, z.name, n(z.trips), pct(z.trips / VALID * 100, 2)]), [7, 51, 22, 20], {right: [2, 3]}),
  caption('Table 9.1 — Top 10 pickup zones. Together they account for ' + pct(topZonesShare, 1) + ' of all trips.'),
  table(['#', 'Zone', 'Trips'], D.bottom10_zones.map(z => [z.rank, z.name, n(z.trips)]),
    [7, 73, 20], {right: [2]}),
  caption('Table 9.2 — Bottom 10 pickup zones.'),
  P('The distribution is extraordinarily skewed. The busiest zone records ' + n(D.top10_zones[0].trips) + ' pickups; the quietest records ' + D.bottom10_zones[0].trips + '. Every zone in the top ten is in Manhattan or is an airport, and every zone in the bottom ten is an outer-borough or industrial area. For a fleet operator this means the coverage question and the revenue question are different questions: the bottom ten zones are, in aggregate, statistically indistinguishable from zero, and a service-obligation argument rather than a commercial one would be needed to serve them.'),
  H2('9.4 (d) Revenue by pickup zone'),
  RP([['Job ', {}], ['05-RevenueByPickupZone-STAGE1', {code: true}], [' · ' + revJob.app + ' · ' + revJob.elapsed + ' s', {}]]),
  RP([['Total revenue across the quarter was ', {}], [usd(D.revenue_total), {bold: true}],
      [', of which ' + usd(D.fare_total) + ' was metered fare and ' + usd(D.tips_total) + ' was recorded tips.', {}]]),
  table(['#', 'Zone', 'Trips', 'Revenue', 'Avg fare', 'Avg dist'], D.top10_revenue.map(z =>
    [z.rank, z.name, n(z.trips), usd(z.revenue, 0), usd(z.avg_fare), z.avg_dist.toFixed(2) + ' mi']),
    [5, 36, 14, 18, 13, 14], {right: [2, 3, 4, 5]}),
  caption('Table 9.3 — Top 10 pickup zones by total revenue, produced by the stage-2 job (Section 10).'),
  P('Compare Table 9.3 with Table 9.1 and the central commercial insight of this report appears. JFK Airport is only fourth by trip count but first by revenue, generating ' + usd(D.top10_revenue[0].revenue, 0) + ' — ' + (D.top10_revenue[0].revenue / D.top10_revenue[3].revenue).toFixed(1) + ' times the revenue of Upper East Side South, which makes more trips. The reason is in the last two columns: the average JFK trip runs ' + D.top10_revenue[0].avg_dist.toFixed(1) + ' miles and bills ' + usd(D.top10_revenue[0].avg_fare) + ', against roughly two miles and fourteen dollars for a Manhattan zone.'),
  P('Ranking zones by trip count and ranking them by revenue produce materially different answers, and only the second one is about the business.'),
  figure('07_revenue_vs_distance.png', 530, 306),
  caption('Figure 9.7 — Revenue versus distance, one dot per pickup zone with at least 500 trips; dot area is trip volume.'),
  P('Figure 9.7 plots the underlying mechanism across all ' + D.n_zones + ' zones. The relationship between a zone’s average trip distance and its average revenue per trip is close to linear, which is unsurprising — the meter charges by distance. What the chart adds is the position of the volume. The largest dots, the highest-traffic zones, cluster tightly in the bottom-left: two-mile trips billing in the low twenties. The two airports sit alone in the top-right, on their own stretch of the same line, and there is almost nothing in between. That gap is a real structural fact about the market rather than an artefact of the sample: New York yellow-taxi demand is two distinct products that happen to share a vehicle fleet.'),
  H2('9.5 (e) Payment method analysis'),
  RP([['Job ', {}], ['06-PaymentMethodAnalysis', {code: true}], [' · ' + byLog['15_job_payment'].app + ' · ' + byLog['15_job_payment'].elapsed + ' s', {}]]),
  figure('04_revenue_by_payment.png', 545, 255),
  caption('Figure 9.4 — Total revenue by payment method.'),
  table(['Payment type', 'Trips', 'Revenue', 'Avg fare', 'Avg tip', '% trips tipped'],
    D.payment.map(p => [p.label, n(p.trips), usd(p.revenue, 0), usd(p.avg_fare),
                        usd(p.avg_tip), pct(p.pct_tipped, 1)]),
    [22, 15, 19, 14, 13, 17], {right: [1, 2, 3, 4, 5]}),
  caption('Table 9.4 — Payment behaviour. "FlexFare" is payment_type 0, a category that appears in the 2026 feed.'),
  RP([['Credit card is the dominant channel: ' + n(D.payment[0].trips) + ' trips and ' + usd(D.payment[0].revenue, 0) + ', which is ' + pct(D.payment[0].revenue / D.payment_revenue_total * 100, 1) + ' of all revenue. ', {}],
      ['The tipping figures, however, must be read with a hard caveat.', {bold: true}]]),
  P('The meter only records a tip when it is charged to the card. A cash tip is handed to the driver and never enters the data. So the cash row’s average tip of ' + usd(cashRow.avg_tip) + ' and its ' + pct(cashRow.pct_tipped, 2) + ' tipping rate are measurement artefacts of the collection method, not evidence that cash customers do not tip. The only defensible statement is the narrow one: among card payers, ' + pct(D.payment[0].pct_tipped, 1) + ' tip, at an average of ' + usd(D.payment[0].avg_tip) + ', or ' + pct(D.payment[0].tip_rate, 1) + ' of the fare.'),
  P('The FlexFare category is the genuinely new finding. It carries ' + n(flexRow.trips) + ' trips and the highest average fare of any category (' + usd(flexRow.avg_fare) + '), yet only ' + pct(flexRow.pct_tipped, 1) + ' of those trips record a tip. That combination — high fares, almost no recorded tips — is consistent with a pre-negotiated or app-brokered fare where any gratuity is handled outside the meter, and it means roughly ' + pct(flexRow.revenue / D.payment_revenue_total * 100, 0) + ' of revenue sits in a channel whose tipping behaviour this dataset simply cannot see.'),
  H2('9.6 (f) Distance-based fare analysis'),
  RP([['Job ', {}], ['07-DistanceBasedFareAnalysis', {code: true}], [' · ' + byLog['16_job_distance'].app + ' · ' + byLog['16_job_distance'].elapsed + ' s', {}]]),
  figure('05_trips_by_distance.png', 530, 269),
  caption('Figure 9.5 — Trips by distance band, with average fare printed on each bar.'),
  table(['Band', 'Trips', 'Revenue', 'Avg fare', 'Avg $/mile', 'Avg speed'],
    D.distance.map(x => [x.band, n(x.trips), usd(x.revenue, 0), usd(x.avg_fare),
                         usd(x.fare_per_mile), x.mph.toFixed(1) + ' mph']),
    [15, 17, 19, 14, 17, 18], {right: [1, 2, 3, 4, 5]}),
  caption('Table 9.5 — Distance bands. Dollars per mile and speed are ratios of sums, not means of ratios — see below.'),
  P('Short trips dominate utterly: ' + pct(D.distance[0].trips / VALID * 100, 1) + ' of all trips are under two miles, and ' + pct((D.distance[0].trips + D.distance[1].trips) / VALID * 100, 1) + ' are under five. The 20-plus mile band is only ' + pct(D.distance[4].trips / VALID * 100, 2) + ' of trips.'),
  RP([['The economics run the other way. The highest ', {}], ['average fare', {italics: true}],
      [' is in the 20-plus mile band (' + usd(D.distance[4].avg_fare) + '), but the highest ', {}],
      ['fare per mile', {italics: true}],
      [' is in the 0–2 mile band (' + usd(D.distance[0].fare_per_mile) + ' against ' + usd(D.distance[4].fare_per_mile) + ') — nearly three times as much per mile. Short trips are where the flag-drop charge dominates, and they are also where the average speed collapses to ' + D.distance[0].mph.toFixed(1) + ' mph. A two-mile Manhattan crawl bills well per mile and badly per hour.', {}]]),
  P('One methodological note that materially affects these numbers: fare-per-mile and speed are computed in the reducer as a ratio of the summed fare to the summed distance, not as the mean of each trip’s own ratio. The alternative would let a handful of 0.01-mile trips with a minimum fare register ratios in the hundreds and drag the band average with them. Aggregating first is the difference between a robust figure and a meaningless one.'),
  H2('9.7 (g) Busiest pickup–drop-off routes'),
  RP([['Jobs ', {}], ['08-BusiestPickupDropoffRoutes', {code: true}], [' and the two Top-20 stage-2 jobs · ' + n(D.n_routes) + ' distinct routes were observed.', {}]]),
  figure('06_top10_routes.png', 560, 263),
  caption('Figure 9.6 — Top 10 routes by trip count.'),
  table(['#', 'Route', 'Trips', 'Revenue', 'Avg fare'],
    D.top20_routes_trips.slice(0, 10).map(r =>
      [r.rank, r.route, n(r.trips), usd(r.revenue, 0), usd(r.avg_rev)]),
    [6, 46, 16, 18, 14], {right: [2, 3, 4]}),
  caption('Table 9.6 — Top 10 routes by trip count.'),
  table(['#', 'Route', 'Revenue', 'Trips', 'Avg fare'],
    D.top20_routes_revenue.slice(0, 10).map(r =>
      [r.rank, r.route, usd(r.revenue, 0), n(r.trips), usd(r.avg_rev)]),
    [6, 46, 18, 16, 14], {right: [2, 3, 4]}),
  caption('Table 9.7 — Top 10 routes by total revenue. Note how little this list overlaps with Table 9.6.'),
  RP([['Of the top 20 routes by trip count and the top 20 by revenue, only ', {}],
      [D.routes_overlap.length + ' routes appear in both lists', {bold: true}],
      ['. The volume list is Upper East Side to Upper East Side and Midtown to Midtown — one-mile hops averaging roughly ' + usd(D.top20_routes_trips[0].avg_rev) + '. The revenue list is led by JFK Airport to outside NYC (' + usd(D.top20_routes_revenue[0].revenue, 0) + ' from only ' + n(D.top20_routes_revenue[0].trips) + ' trips, averaging ' + usd(D.top20_routes_revenue[0].avg_rev) + ' each).', {}]]),
  P('The single most frequent route in the entire quarter, ' + D.top20_routes_trips[0].route + ', made ' + n(D.top20_routes_trips[0].trips) + ' trips and earned ' + usd(D.top20_routes_trips[0].revenue, 0) + '. The JFK-to-outside-NYC route made ' + n(D.top20_routes_revenue[0].trips) + ' trips — under a third as many — and earned ' + usd(D.top20_routes_revenue[0].revenue, 0) + ', more than twice as much. A dispatch strategy optimised on trip frequency would systematically send vehicles to the wrong place.'),
  H2('9.8 (h) Trip duration analysis'),
  RP([['Job ', {}], ['09-TripDurationAnalysis', {code: true}], [' · ' + byLog['18_job_duration'].app + ' · ' + byLog['18_job_duration'].elapsed + ' s', {}]]),
  table(['Duration band', 'Trips', 'Revenue', 'Avg fare', 'Avg dist', 'Avg tip', 'Avg speed'],
    D.duration.map(x => [x.band, n(x.trips), usd(x.revenue, 0), usd(x.avg_fare),
                         x.avg_dist.toFixed(2) + ' mi', usd(x.avg_tip), x.mph.toFixed(1) + ' mph']),
    [15, 14, 17, 12, 13, 12, 17], {right: [1, 2, 3, 4, 5, 6]}),
  caption('Table 9.8 — Trip duration bands. Duration is a derived field, computed map-side from the two timestamps.'),
  P('The modal trip is 10–20 minutes (' + n(D.duration[2].trips) + ' trips, ' + pct(D.duration[2].trips / VALID * 100, 1) + '). Fare rises monotonically with duration, as it must, but the interesting column is speed: it is lowest in the shortest band (' + D.duration[0].mph.toFixed(1) + ' mph) and in the longest (' + D.duration[5].mph.toFixed(1) + ' mph), and highest in the 30–60 minute band (' + D.duration[4].mph.toFixed(1) + ' mph).'),
  P('That U-shape is congestion made visible. Very short trips are stop-start crawls within a dense grid; 30–60 minute trips are the airport and bridge runs that spend most of their time on open road; and the 60-plus minute band drops back to ' + D.duration[5].mph.toFixed(1) + ' mph because it is dominated by trips stuck in genuinely bad traffic rather than by longer distances — note that its average distance (' + D.duration[5].avg_dist.toFixed(1) + ' mi) is barely different from the 30–60 band’s (' + D.duration[4].avg_dist.toFixed(1) + ' mi) while taking more than twice as long.'),
  H2('9.9 (i) Anomaly detection'),
  RP([['Job ', {}], ['10-AnomalyDetection-RawFeed', {code: true}], [' · ' + byLog['19_job_anomaly'].app + ' · ' + byLog['19_job_anomaly'].elapsed + ' s. ', {}],
      ['This job deliberately reads the RAW input, not the cleaned dataset', {bold: true}],
      [', because its purpose is to measure how much of the original feed is suspicious.', {}]]),
  table(['Anomaly', 'Records', '% of raw'],
    D.anomalies.map(a => [a.label, n(a.count), pct(a.pct, 4)]), [46, 27, 27], {right: [1, 2]}),
  caption('Table 9.9 — Anomaly detector results over all ' + n(D.anom_total) + ' raw records. A record may trigger several detectors, so the column sums to more than the flagged total.'),
  RP([[n(D.anom_flagged[0]) + ' records (' + pct(D.anom_flagged[1], 2) + ')', {bold: true}],
      [' triggered at least one detector. That headline number is dominated by a single detector and should not be read as "31% of the data is corrupt".', {}]]),
  bulletRich([['ZERO_PASSENGER (' + pct(D.anomalies.find(a => a.label === 'ZERO_PASSENGER').pct, 1) + ') is the whole story. ', {bold: true}],
    ['It is a missing driver-entered field, not a corrupt trip. Excluding it, the genuinely suspect share falls to roughly 4%.']]),
  bulletRich([['ZERO_DISTANCE (' + n(D.anomalies.find(a => a.label === 'ZERO_DISTANCE').count) + ') ', {bold: true}],
    ['is the largest real defect: a meter that was never engaged, or a trip cancelled at the kerb.']]),
  bulletRich([['NEGATIVE_FARE and NEGATIVE_TOTAL (' + n(D.anomalies.find(a => a.label === 'NEGATIVE_FARE').count) + ' and ' + n(D.anomalies.find(a => a.label === 'NEGATIVE_TOTAL').count) + ') ', {bold: true}],
    ['are almost certainly refund and void rows written as negative counterparts to an earlier trip. They are not errors in the taxi system; they are errors only if summed into revenue — which is exactly why the cleaning job removes them.']]),
  bulletRich([['EXTREME_FARE_PER_MI (' + n(D.anomalies.find(a => a.label === 'EXTREME_FARE_PER_MI').count) + ') ', {bold: true}],
    ['catches the 0.01-mile trip billed at the minimum fare — a meter artefact rather than a fraud signal, and the reason Section 9.6 aggregates before dividing.']]),
  bulletRich([['IMPOSSIBLE_SPEED (' + n(D.anomalies.find(a => a.label === 'IMPOSSIBLE_SPEED').count) + ') and EXTREME_DURATION (' + n(D.anomalies.find(a => a.label === 'EXTREME_DURATION').count) + ') ', {bold: true}],
    ['are rare enough to be individually investigable — the right outcome for a fraud or fault detector.']]),
  H2('9.10 Verification of every result'),
  P('Aggregates computed by twenty-two hand-written Python programs across a distributed framework deserve to be checked rather than trusted. Every figure in this section was therefore re-computed independently with Pandas, directly from the same cleaned dataset, by a script that shares no code with any mapper or reducer.'),
  evidence('evidence/E7_verification.txt', 5, 24),
  caption('Evidence 9.1 — scripts/verify_results.py (extract). The full output, covering routes, payment types, distance and duration bands and cross-analysis totals, is in evidence/E7_verification.txt.'),
  P('All 24 hourly counts, all 7 day-of-week counts, the ' + D.n_zones + ' zone aggregates, the ' + n(D.n_routes) + ' route aggregates and every revenue total match to the cent, and both Top-N rankings return the same zones in the same order as a Pandas nlargest. The five analyses that partition the trips independently — daily, locations, distance, duration and payment — each sum to exactly ' + n(VALID) + ', which is the arithmetic they must satisfy if no record was dropped or double-counted at a block boundary.'),
];

// ============================================================ 10. MULTI-STAGE
const s2job = byLog['20_job_top10_revenue_zones'];
const s10 = [
  H1('10. Multi-Stage MapReduce'),
  P('The compulsory two-stage workflow is the Top-10 revenue ranking. It exists for a real reason rather than as an exercise: as Section 7.3 explains, no single mapper or reducer in stage 1 can see a global ordering, so ranking genuinely requires a second job.'),
  H2('10.1 The pipeline'),
  table(['', 'Stage 1', 'Stage 2'], [
    ['Job name', '05-RevenueByPickupZone-STAGE1', '11-Top10RevenueZones-STAGE2'],
    ['Application', revJob.app, s2job.app],
    ['Input', '/taxi_project/input/cleaned', '/taxi_project/output/revenue'],
    ['Output', '/taxi_project/output/revenue', '/taxi_project/output/top10_revenue_zones'],
    ['Map input records', n(revJob.map_in), n(s2job.map_in)],
    ['Reduce output records', n(revJob.red_out), n(s2job.red_out)],
    ['Reducers', String(revJob.reds), String(s2job.reds) + ' (mandatory)'],
    ['Elapsed', revJob.elapsed + ' s', s2job.elapsed + ' s'],
  ], [22, 39, 39]),
  caption('Table 10.1 — The two stages. Stage 2’s input is stage 1’s output directory: HDFS is the hand-off medium.'),
  P('Stage 2 reads ' + n(s2job.map_in) + ' records — one per zone — rather than the ' + n(revJob.map_in) + ' trips that stage 1 read, and finishes in ' + s2job.elapsed + ' seconds against ' + revJob.elapsed + '. That is the point of decomposing the work: the expensive aggregation happens once, and the cheap ranking runs against its result.'),
  H2('10.2 The intermediate HDFS output'),
  P('This is what stage 1 leaves in HDFS and what stage 2 consumes:'),
  evidence('evidence/E5_multistage_output.txt', 2, 17),
  caption('Evidence 10.1 — Stage-1 intermediate output in HDFS.'),
  H2('10.3 The final stage-2 result'),
  evidence('evidence/E5_multistage_output.txt', 20, 34),
  caption('Evidence 10.2 — Stage-2 output: the global Top 10 by revenue.'),
  H2('10.4 The Top-N pattern'),
  P('A naive stage 2 would send every stage-1 row to a single reducer and sort there. Instead each mapper keeps its own local heap of the best N rows it has seen and emits only those N when its input is exhausted — the in-mapper combining pattern.'),
  pyfile('mappers/mapper_topn.py', {stripDoc: true, from: 4}),
  caption('Listing 10.1 — mappers/mapper_topn.py. With M map tasks the single reducer receives at most M x N candidates instead of the whole table.'),
  RP([['The reducer is the only place in the entire pipeline that sees a global ordering, which is why the job must run with ', {}],
      ['-D mapreduce.job.reduces=1', {code: true}],
      ['. With two reducers there would be two partial rankings and no global answer. This serial final step is the deliberate trade the Top-N pattern makes — acceptable precisely because the candidate set has already been reduced to a few dozen rows.', {}]]),
  H2('10.5 Reuse'),
  P('The same generic mapper/reducer pair, parameterised only through environment variables, produced five different rankings from three different stage-1 jobs:'),
  table(['Stage-2 job', 'Reads', 'Ranks by', 'Elapsed'], stage2.map(j => {
    const m = {'11-Top10RevenueZones-STAGE2': ['output/revenue', 'total revenue, top 10'],
               '12-Top10PickupZonesByTrips': ['output/locations', 'trip count, top 10'],
               '13-Bottom10PickupZonesByTrips': ['output/locations', 'trip count, bottom 10'],
               '14-Top20RoutesByTripCount': ['output/routes', 'trip count, top 20'],
               '15-Top20RoutesByRevenue': ['output/routes', 'total revenue, top 20']}[j.name];
    return [j.name, m[0], m[1], j.elapsed + ' s'];
  }), [34, 22, 30, 14], {right: [3]}),
];

// ============================================================ 11. YARN
const totalCpu = jobs.reduce((a, j) => a + (j.cpu_ms || 0), 0);
const s11 = [
  H1('11. YARN Analysis'),
  P('Every job in this project was submitted to YARN, which allocated containers, launched the ApplicationMaster and the map and reduce tasks, and reported final status. Nothing ran outside the resource manager.'),
  H2('11.1 All applications'),
  table(['Application ID', 'Job name', 'Maps', 'Reds', 'Elapsed'],
    jobs.map(j => [j.app.replace('application_1788022068759_', '..._'), j.name,
                   String(j.maps || '—'), String(j.reds || '—'), j.elapsed + ' s']),
    [16, 46, 11, 11, 16], {right: [2, 3, 4], size: 14}),
  caption('Table 11.1 — All ' + jobs.length + ' MapReduce applications (' + pipelineJobs.length + ' pipeline jobs plus ' + (jobs.length - pipelineJobs.length) + ' benchmark runs). Every one finished with State=FINISHED, Final-State=SUCCEEDED.'),
  H2('11.2 Application detail from the ResourceManager'),
  grepEvidence('evidence/E4_yarn_applications.txt',
    ['Application-Id :', 'Application-Name :', 'Application-Type :', 'State :', 'Final-State :',
     'Started :', 'Finished :', 'Aggregate Resource Allocation', 'AM Host', 'Queue :'], 14),
  caption('Evidence 11.1 — yarn application -status (extract). Aggregate Resource Allocation is YARN’s own accounting of MB-seconds and vcore-seconds consumed.'),
  H2('11.3 Node state'),
  grepEvidence('evidence/E4_yarn_applications.txt', ['Node-Id', 'localhost:36319', 'localhost:46727'], 4),
  caption('Evidence 11.2 — yarn node -list -all. The SHUTDOWN entry is the NodeManager instance that was restarted after the disk-health fix described in Section 4.3; the RUNNING entry served every job in this report.'),
  H2('11.4 What YARN actually did'),
  P('For a typical analytical job on the cleaned dataset, YARN allocated:'),
  bulletRich([['One ApplicationMaster container ', {bold: true}], ['(1,024 MB) to coordinate the job.']]),
  bulletRich([[String(revJob.maps) + ' map containers ', {bold: true}],
    ['(1,024 MB each). The cleaned dataset occupies 10 HDFS blocks, so 10 splits were scheduled; the eleventh container is a re-run attempt, which is YARN doing exactly what it exists to do.']]),
  bulletRich([[String(revJob.reds) + ' reduce container ', {bold: true}], ['(1,024 MB).']]),
  P('The NodeManager was configured with 5,120 MB and 4 vcores, so at most four containers plus the ApplicationMaster could run at once. With only 2 physical cores, the practical parallelism was lower than the configured parallelism — which is precisely the constraint that Section 12 quantifies. Across all ' + jobs.length + ' jobs, YARN accounted for ' + n(totalCpu / 1000) + ' seconds of CPU time.'),
  P('The ResourceManager web interface at http://localhost:8088/cluster shows the same information graphically, and the REST endpoint /ws/v1/cluster/apps was captured into the evidence directory so the application records survive the cluster being shut down.'),
];

// ============================================================ 12. PERFORMANCE
const pandasFull = 13.52, pandasChunk = 10.96, pandasPeak = 1347.4, pandasChunkPeak = 200.2;
const hadoopFixed = tinyJob.elapsed;
const marginalHadoop = ((benchJob.elapsed - hadoopFixed) / (VALID / 1e6)).toFixed(1);
const marginalPandas = ((pandasChunk - 0.15) / (VALID / 1e6)).toFixed(2);
const s12 = [
  H1('12. Performance Comparison'),
  P('The comparison uses one analysis run two ways: revenue by pickup zone — trip count, total fare, total tips, total revenue, average fare and average distance, grouped by PULocationID — over the identical ' + n(VALID) + ' cleaned records. On the Hadoop side that is mapper_revenue.py with combiner_sums.py and reducer_revenue.py. On the Pandas side it is a groupby over the same columns. Both produce the same ' + D.n_zones + ' groups.'),
  H2('12.1 The headline table'),
  table(['Metric', 'Python / Pandas', 'Hadoop MapReduce'], [
    ['Dataset size', '1.03 GB (2 CSV part files)', '1.03 GB in HDFS (' + benchJob.maps + ' blocks)'],
    ['Number of records', n(VALID), n(VALID)],
    ['Execution time', pandasChunk.toFixed(2) + ' s chunked / ' + pandasFull.toFixed(2) + ' s full load',
                       benchJob.elapsed + ' s'],
    ['Memory used', n(pandasChunkPeak, 0) + ' MB chunked / ' + n(pandasPeak, 0) + ' MB full load',
                    n((benchJob.peak_map_mem || 0) / 1048576, 0) + ' MB peak map, ' +
                    n((benchJob.peak_red_mem || 0) / 1048576, 0) + ' MB peak reduce'],
    ['Mapper tasks', '— (single process)', String(benchJob.maps)],
    ['Reducer tasks', '—', String(benchJob.reds)],
    ['Output size', D.n_zones + ' rows', D.n_zones + ' rows'],
    ['Parallelism', '1 thread', String(benchJob.maps) + ' map tasks, up to 4 concurrent containers'],
    ['CPU time (framework-reported)', '—', n((benchJob.cpu_ms || 0) / 1000, 1) + ' s'],
  ], [24, 38, 38]),
  caption('Table 12.1 — The required comparison table. Hadoop job ' + benchJob.app + ', run with nothing else on the cluster.'),
  RP([['Pandas is ', {}], [(benchJob.elapsed / pandasChunk).toFixed(0) + ' times faster', {bold: true}],
      [' than Hadoop on this dataset, on this machine. That is the measured result, and it is also the ', {}],
      ['expected', {italics: true}], [' result. Reporting it honestly is more useful than engineering a comparison that flatters Hadoop.', {}]]),
  H2('12.2 Why — a three-point scaling measurement'),
  P('A single data point cannot distinguish "Hadoop is slow" from "Hadoop has fixed overhead". So the identical analysis was run at three scales on both systems.'),
  table(['Scale', 'Records', 'Hadoop', 'Pandas (chunked)', 'Ratio'], [
    ['Tiny', n(100000), tinyJob.elapsed + ' s', '0.15 s', (tinyJob.elapsed / 0.15).toFixed(0) + 'x'],
    ['Half', n(5248143), halfJob.elapsed + ' s', '6.00 s', (halfJob.elapsed / 6.0).toFixed(0) + 'x'],
    ['Full', n(VALID), benchJob.elapsed + ' s', pandasChunk.toFixed(2) + ' s',
            (benchJob.elapsed / pandasChunk).toFixed(0) + 'x'],
  ], [16, 22, 20, 24, 18], {right: [1, 2, 3, 4]}),
  caption('Table 12.2 — Scaling behaviour. The ratio narrows as the data grows, which is the whole argument.'),
  P('Two numbers fall straight out of this table.'),
  bulletRich([['Hadoop’s fixed overhead is about ' + hadoopFixed + ' seconds. ', {bold: true}],
    ['A job over 100,000 records — essentially no work — still takes ' + hadoopFixed + ' s. That is the cost of submitting to the ResourceManager, allocating and launching an ApplicationMaster container, launching map and reduce JVMs, running the shuffle machinery and committing output. It is paid in full whether the input is 10 MB or 10 TB.']]),
  bulletRich([['Hadoop’s marginal cost is about ' + marginalHadoop + ' seconds per million records ', {bold: true}],
    ['on this 2-core node, against roughly ' + marginalPandas + ' s per million for Pandas. Per record, in a single process, Pandas is genuinely faster — its aggregation runs in vectorised C over typed NumPy arrays, while every Hadoop record is serialised to text, parsed by a Python process, written to a sort buffer and read back.']]),
  P('Notice, though, that the ratio falls from ' + (tinyJob.elapsed / 0.15).toFixed(0) + ' times to ' + (benchJob.elapsed / pandasChunk).toFixed(0) + ' times across two orders of magnitude of data. The gap is closing, and it closes because the fixed cost is being amortised.'),
  H2('12.3 Where the crossover actually is'),
  P('Speed is the wrong axis on which to make the decision. The right one is the ceiling, and the ceiling is visible in the memory column.'),
  P('The full-load Pandas variant — the one a data scientist writes first — peaked at ' + n(pandasPeak, 0) + ' MB of resident memory for 1.03 GB of CSV, a factor of about ' + (pandasPeak / 1024 / 1.03).toFixed(2) + '. On this 8 GB machine that hits the wall at roughly 6 GB of CSV, or about 60 million trip records, which is a bit over one year of yellow-taxi data. Add the green-taxi and for-hire-vehicle feeds, or ask for two years, and the program does not get slower; it fails.'),
  P('The chunked Pandas variant avoids that, holding a bounded ' + n(pandasChunkPeak, 0) + ' MB by streaming the file and accumulating partial group sums. But look at what it is: a hand-written, single-threaded MapReduce. It has a map step (per-chunk groupby), a combine step (partial aggregation) and a reduce step (concatenate and sum by level). Writing it means reimplementing, badly and without fault tolerance, the thing Hadoop already provides — and it is still pinned to one core on one machine.'),
  P('Hadoop’s ' + marginalHadoop + ' s per million is a per-node figure. It is divided by the number of nodes. Ten machines would put this job near the ' + hadoopFixed + '-second floor; Pandas on ten machines is still Pandas on one machine, because there is no mechanism in it that uses the other nine.'),
  H2('12.4 The decision rule'),
  table(['Use', 'When'], [
    ['Pandas / single machine', 'The data fits comfortably in RAM with room for intermediates — in practice under a few GB. Interactive, exploratory, iterative work. Fastest path to an answer, by a wide margin.'],
    ['Hadoop MapReduce', 'The data exceeds one machine’s memory or disk; the job must survive node failure without restarting from scratch; the work is a scheduled batch pass over historical data where a fixed one-minute overhead is irrelevant; or the volume is growing and the architecture must scale by adding machines rather than by buying a bigger one.'],
  ], [26, 74]),
  P('For this specific quarter of taxi data on this specific machine, Pandas is the correct engineering choice, and the honest conclusion of the benchmark is to say so. The reason to build the Hadoop pipeline is that the same code, unchanged, runs against ten years of data on a fifty-node cluster — and the Pandas script does not run against it at all.'),
  P('One caveat in Hadoop’s favour that Table 12.1 understates: the cleaning job (Section 6) shuffled a full gigabyte to deduplicate ' + n(RAW) + ' records. A Pandas equivalent would need every record resident simultaneously to detect duplicates, at roughly 1.3 GB per gigabyte of input. The distributed version has no such requirement, because the deduplication happens inside a sort that is allowed to spill to disk.'),
];

// ============================================================ 13. INSIGHTS
const airportRev = D.top10_revenue[0].revenue + D.top10_revenue[1].revenue;
const airportTrips = D.top10_revenue[0].trips + D.top10_revenue[1].trips;
const q = (label, question, answers) => [H3(label + ' ' + question), ...answers.map(a => P(a))];
const s13 = [
  H1('13. Business Insights'),
  P('The twelve questions posed by the case study, answered from the results above.'),
  ...q('(a)', 'What is the busiest hour for taxi demand?',
    [D.hour_peak[0] + ':00, with ' + n(D.hour_peak[1]) + ' trips — ' + pct(D.hour_peak[1] / VALID * 100, 2) + ' of the quarter. The quietest is ' + D.hour_low[0] + ':00 with ' + n(D.hour_low[1]) + '. More useful than the peak itself is the plateau: every hour from 12:00 to 22:00 exceeds half a million trips, so there is no single hour worth optimising for.']),
  ...q('(b)', 'What is the busiest day of the week?',
    [D.day_peak.day + ' (' + n(D.day_peak.trips) + ' trips); the quietest is ' + D.day_low.day + ' (' + n(D.day_low.trips) + '). Per day, the weekend averages ' + n(D.weekend_avg) + ' trips against ' + n(D.weekday_avg) + ' on weekdays — ' + pct((D.weekend_avg / D.weekday_avg - 1) * 100, 1) + ' busier, which the raw weekday-versus-weekend totals hide.']),
  ...q('(c)', 'Which pickup zones generate the most trips?',
    [D.top10_zones.slice(0, 3).map(z => z.name).join(', ') + ' lead, and the top ten zones account for ' + pct(topZonesShare, 1) + ' of all ' + n(VALID) + ' trips. All ten are Manhattan zones or airports.']),
  ...q('(d)', 'Which pickup zones generate the most revenue?',
    ['A different list. ' + D.top10_revenue[0].name + ' is first with ' + usd(D.top10_revenue[0].revenue, 0) + ' despite ranking only fourth by trip count, followed by ' + D.top10_revenue[1].name + ' (' + usd(D.top10_revenue[1].revenue, 0) + '). The two airports alone contribute ' + usd(airportRev, 0) + ' — ' + pct(airportRev / D.revenue_total * 100, 1) + ' of all revenue — from ' + pct(airportTrips / VALID * 100, 1) + ' of the trips.']),
  ...q('(e)', 'Which payment method contributes the most revenue?',
    ['Credit card: ' + usd(D.payment[0].revenue, 0) + ', or ' + pct(D.payment[0].revenue / D.payment_revenue_total * 100, 1) + ' of the total, across ' + n(D.payment[0].trips) + ' trips. Cash has fallen to ' + pct(cashRow.revenue / D.payment_revenue_total * 100, 1) + '.']),
  ...q('(f)', 'Do credit-card users generate more tips?',
    ['In the data, overwhelmingly: card trips average ' + usd(D.payment[0].avg_tip) + ' in tips with ' + pct(D.payment[0].pct_tipped, 1) + ' of trips tipping, against effectively zero for cash.',
     'But this comparison is not valid as a statement about customer behaviour. The meter records a tip only when it is charged to the card; a cash tip never enters the dataset. The defensible claim is the narrow one — among card payers, ' + pct(D.payment[0].pct_tipped, 1) + ' tip at ' + pct(D.payment[0].tip_rate, 1) + ' of fare. Any statement about whether cash customers tip requires data this system does not collect.']),
  ...q('(g)', 'What distance category produces the highest average fare?',
    ['The 20-plus mile band, at ' + usd(D.distance[4].avg_fare) + ' per trip — but it is only ' + pct(D.distance[4].trips / VALID * 100, 2) + ' of trips. Per mile the ranking inverts: 0–2 mile trips earn ' + usd(D.distance[0].fare_per_mile) + ' per mile against ' + usd(D.distance[4].fare_per_mile) + ' for the longest band. Long trips are the biggest tickets; short trips are the best rate.']),
  ...q('(h)', 'What are the most frequently travelled routes?',
    [D.top20_routes_trips.slice(0, 3).map(r => r.route + ' (' + n(r.trips) + ')').join('; ') + '. All are short intra-Manhattan hops averaging around a mile.']),
  ...q('(i)', 'Are the most frequent routes also the most profitable?',
    ['No, and this is the most actionable finding in the report. Only ' + D.routes_overlap.length + ' routes appear in both the top 20 by trips and the top 20 by revenue.',
     'The busiest route (' + D.top20_routes_trips[0].route + ') earned ' + usd(D.top20_routes_trips[0].revenue, 0) + ' from ' + n(D.top20_routes_trips[0].trips) + ' trips. The highest-earning route (' + D.top20_routes_revenue[0].route + ') earned ' + usd(D.top20_routes_revenue[0].revenue, 0) + ' from just ' + n(D.top20_routes_revenue[0].trips) + ' — ' + (D.top20_routes_revenue[0].avg_rev / D.top20_routes_trips[0].avg_rev).toFixed(0) + ' times the revenue per trip. Optimising dispatch on frequency would send vehicles to the wrong side of the city.']),
  ...q('(j)', 'What percentage of records contain potential anomalies?',
    [pct(D.anom_flagged[1], 2) + ' of the raw feed triggered at least one detector (' + n(D.anom_flagged[0]) + ' records). That figure needs decomposing before it is quoted: ' + pct(D.anomalies.find(a => a.label === 'ZERO_PASSENGER').pct, 1) + ' is a missing passenger_count, which is a blank field rather than a bad trip. Excluding it, genuinely defective records are about 4% — dominated by zero distances (' + pct(D.anomalies.find(a => a.label === 'ZERO_DISTANCE').pct, 2) + ') and negative amounts (' + pct(D.anomalies.find(a => a.label === 'NEGATIVE_TOTAL').pct, 2) + '), the latter being refund rows rather than errors.']),
  ...q('(k)', 'What transportation insights can management derive?',
    ['Position for the evening, not the morning. There is no morning commuter peak; demand builds through the afternoon and holds from 12:00 to 22:00. Shift patterns built around a split morning/evening rush are mismatched to the data.',
     'Treat the airports as a separate business. JFK and LaGuardia produce ' + pct(airportRev / D.revenue_total * 100, 1) + ' of revenue from a small minority of trips, at average fares of ' + usd(D.top10_revenue[0].avg_fare) + ' and ' + usd(D.top10_revenue[1].avg_fare) + '. Airport queue management deserves its own operating policy.',
     'Manage the two products differently. Short Manhattan hops are a high-frequency, high-rate-per-mile, low-speed product; airport and outer-borough runs are low-frequency, high-ticket, high-speed. They have different economics and should not share a single utilisation target.',
     'Watch the FlexFare channel. It is already ' + pct(flexRow.revenue / D.payment_revenue_total * 100, 1) + ' of revenue at the highest average fare of any payment type, with almost no recorded tips. Whatever it represents, driver earnings in that channel are not visible in this data.',
     'Fix passenger_count at source. A quarter of the feed is missing it. Any future analysis of occupancy or vehicle sizing is impossible until that collection gap is closed.']),
  ...q('(l)', 'When does Hadoop MapReduce provide a meaningful advantage?',
    ['Not here. At 1.03 GB on one machine, Pandas finished in ' + pandasChunk.toFixed(1) + ' seconds against Hadoop’s ' + benchJob.elapsed + ' — ' + (benchJob.elapsed / pandasChunk).toFixed(0) + ' times faster — and the honest recommendation for this quarter of data is to use Pandas.',
     'The advantage appears at three thresholds. First, when the data no longer fits in memory: the full-load Pandas variant needed ' + n(pandasPeak, 0) + ' MB for 1.03 GB, so an 8 GB machine fails at roughly one year of this feed. Second, when the job must be reliable: a mid-job node failure re-runs one task in MapReduce and restarts the whole script in Pandas. Third, when scale must be bought with machines rather than with a bigger machine — Hadoop’s ' + marginalHadoop + ' s per million records is per node and divides across the cluster; Pandas has no such term.',
     'The ' + hadoopFixed + '-second fixed overhead measured in Section 12.2 is what makes Hadoop the wrong tool for interactive work and an entirely reasonable one for a scheduled nightly pass over years of history.']),
];

// ============================================================ 14. LIMITATIONS
const s14 = [
  H1('14. Limitations'),
  H2('14.1 Of the platform'),
  bulletRich([['Single node. ', {bold: true}], ['A pseudo-distributed cluster demonstrates every mechanism — block splitting, containers, shuffle, fault handling — but it cannot demonstrate the benefit, because there is no second node for a task to move to. All timings in Section 12 are single-node timings and should be read as an upper bound on Hadoop’s cost, not as a measure of its scalability.']]),
  bulletRich([['Two physical cores. ', {bold: true}], ['YARN was configured for 4 vcores, so the configured parallelism exceeded the real parallelism and containers contended for CPU.']]),
  bulletRich([['Replication factor 1. ', {bold: true}], ['With one DataNode, HDFS’s fault tolerance is configured but not exercised. Losing the DataNode would lose the data.']]),
  bulletRich([['No native libraries. ', {bold: true}], ['Java implementations of checksumming and compression were used throughout, which penalises the Hadoop side of the benchmark by an unmeasured amount.']]),
  bulletRich([['Python startup cost. ', {bold: true}], ['Hadoop Streaming forks a Python process per task and serialises every record to text across a pipe. A native Java MapReduce job, or a Spark job over the original Parquet, would avoid both costs — at the price of the readability that made this project practical.']]),
  H2('14.2 Of the data'),
  bulletRich([['Cash tips are invisible. ', {bold: true}], ['The single most important caveat in the report. Every tipping comparison between payment types is a comparison of what the meter records, not of what customers do.']]),
  bulletRich([['passenger_count is ' + pct(rejPct('PASSENGER_FLAGGED'), 1) + ' missing. ', {bold: true}], ['Retained and flagged rather than deleted (Section 6.3), but no occupancy analysis is possible.']]),
  bulletRich([['One quarter, one taxi class. ', {bold: true}], ['January–March 2026 only, yellow taxis only. No seasonal comparison is possible, and no conclusion here extends to green taxis or for-hire vehicles, which serve substantially different geographies.']]),
  bulletRich([['Zones, not coordinates. ', {bold: true}], ['The TLC publishes 263 zone identifiers rather than latitude and longitude, so route analysis is at neighbourhood granularity. Two trips within one large zone are indistinguishable from each other.']]),
  bulletRich([['FlexFare is undocumented here. ', {bold: true}], ['payment_type 0 carries ' + n(flexRow.trips) + ' trips in this feed. Its exact meaning was not verified against a TLC data dictionary, and the interpretation offered in Section 9.5 is an inference from its fare and tip profile, not a documented fact.']]),
  H2('14.3 Of the method'),
  bulletRich([['Thresholds are judgements. ', {bold: true}], ['200 miles, 24 hours, $1,000, 100 mph — each is defensible and none is derived from the data. A different analyst would choose differently and would get slightly different totals. The counters make the sensitivity checkable, which is the point of recording them.']]),
  bulletRich([['Revenue is total_amount. ', {bold: true}], ['It includes tolls, surcharges and taxes, so it is gross receipts rather than driver or operator earnings.']]),
  bulletRich([['Deduplication is exact-match only. ', {bold: true}], ['Two records differing by one cent or one second are treated as distinct trips. A fuzzy near-duplicate detector would need a different key design entirely — for instance locality-sensitive hashing — and would be a considerably harder MapReduce problem.']]),
];

// ============================================================ 15. CONCLUSION
const s15 = [
  H1('15. Conclusion'),
  P('A complete Hadoop analytics pipeline was designed, implemented and executed over ' + n(RAW) + ' NYC yellow-taxi trip records. HDFS stored the 1.1 GB dataset across ten 128 MB blocks; a two-phase MapReduce job validated and deduplicated it down to ' + n(VALID) + ' analysable records; nine analytical jobs and five Top-N jobs, all written as Python programs run through Hadoop Streaming, produced the results in Section 9; and YARN scheduled all ' + jobs.length + ' applications, every one of which succeeded.'),
  P('The analysis itself produced three findings a trip-count summary would have missed. Demand is a broad afternoon-to-evening plateau rather than a commuter peak, and the weekend is busier per day than the weekday once the totals are normalised. Revenue and volume point at different parts of the city — the two airports produce ' + pct(airportRev / D.revenue_total * 100, 1) + ' of revenue from a small fraction of trips. And only ' + D.routes_overlap.length + ' of the top twenty routes by frequency also appear in the top twenty by revenue, which means any dispatch policy tuned on trip counts is optimising the wrong quantity.'),
  P('On the technical side, the exercise made three things concrete that are easy to state and hard to feel. The choice of map output key is the algorithm — a composite key gives a two-column GROUP BY, the whole record as key gives a distributed DISTINCT, and a constant key gives a global ranking at the cost of a serial reduce. Averages are not associative, which is why every mapper here emits sums and counts and why one generic combiner could serve five different analyses, cutting the route job’s shuffle by a factor of ' + (routeCombIn / Math.max(routeCombOut, 1)).toFixed(0) + '. And ranking genuinely cannot be done in a single job, which is why the multi-stage workflow exists for a reason rather than for a mark.'),
  P('The benchmark is the part worth being blunt about. Pandas beat Hadoop by a factor of ' + (benchJob.elapsed / pandasChunk).toFixed(0) + ' on this dataset, and for a single quarter of taxi data on a single machine, Pandas is the right tool. Hadoop’s ' + hadoopFixed + '-second fixed overhead is unrecoverable at this scale. What the three-point scaling measurement shows is where that stops being true: the ratio narrows as data grows, Pandas’ memory ceiling arrives at roughly one year of this feed on an 8 GB machine, and Hadoop’s per-record cost is the only one of the two that divides by the number of nodes. The pipeline built here would run unchanged over ten years of data on fifty machines. The Pandas script would not run over it at all.'),
  P('That is the real lesson of the assignment, and it is not "Hadoop is fast". It is that the interesting property of a distributed system is not its speed on data that fits, but its behaviour on data that does not.'),
];

// ============================================================ 16. REFERENCES
const s16 = [
  H1('16. References'),
  bullet('Apache Software Foundation. Apache Hadoop 3.5.0 Documentation — HDFS Architecture. https://hadoop.apache.org/docs/r3.5.0/hadoop-project-dist/hadoop-hdfs/HdfsDesign.html'),
  bullet('Apache Software Foundation. Hadoop Streaming. https://hadoop.apache.org/docs/r3.5.0/hadoop-streaming/HadoopStreaming.html'),
  bullet('Apache Software Foundation. Apache Hadoop YARN. https://hadoop.apache.org/docs/r3.5.0/hadoop-yarn/hadoop-yarn-site/YARN.html'),
  bullet('Apache Software Foundation. MapReduce Tutorial. https://hadoop.apache.org/docs/r3.5.0/hadoop-mapreduce-client/hadoop-mapreduce-client-core/MapReduceTutorial.html'),
  bullet('Dean, J. and Ghemawat, S. (2004). MapReduce: Simplified Data Processing on Large Clusters. OSDI 2004.'),
  bullet('Ghemawat, S., Gobioff, H. and Leung, S.-T. (2003). The Google File System. SOSP 2003.'),
  bullet('White, T. (2015). Hadoop: The Definitive Guide, 4th edition. O’Reilly Media.'),
  bullet('Leskovec, J., Rajaraman, A. and Ullman, J. (2020). Mining of Massive Datasets, 3rd edition. Cambridge University Press. Chapter 2, MapReduce design patterns.'),
  bullet('NYC Taxi & Limousine Commission. TLC Trip Record Data. https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page'),
  bullet('NYC Taxi & Limousine Commission. Yellow Trips Data Dictionary and Taxi Zone Lookup Table.'),
  bullet('Apache Software Foundation. Apache Parquet Documentation — File Format. https://parquet.apache.org/docs/file-format/'),
  H2('Appendix — Reproducing this work'),
  P('The complete project accompanies this report:'),
  bullet('commands.txt — every HDFS and Hadoop Streaming command, in execution order.'),
  bullet('README.md — environment assumptions, project layout and execution instructions.'),
  bullet('mappers/ and reducers/ — all 22 Python programs.'),
  bullet('evidence/ — one driver log per job, the counter dumps, and the HDFS/YARN evidence files E1–E6.'),
  bullet('output/ — the reducer output behind every table and figure in this report.'),
  bullet('charts/ — the seven figures, generated by scripts/make_charts.py from output/.'),
];

// ================================================================== ASSEMBLE
const doc = new Document({
  creator: 'Big Data Essentials - Individual Assignment',
  title: 'Distributed Taxi Trip Analytics Using Apache Hadoop, HDFS and Python MapReduce',
  description: 'NYC TLC yellow taxi trip records, January-March 2026',
  features: {updateFields: true},
  numbering: {config: [{
    reference: 'bullets',
    levels: [
      {level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT,
       style: {paragraph: {indent: {left: 360, hanging: 220}}}},
      {level: 1, format: LevelFormat.BULLET, text: '–', alignment: AlignmentType.LEFT,
       style: {paragraph: {indent: {left: 720, hanging: 220}}}}]}]},
  styles: {default: {document: {run: {font: 'Calibri', size: 20, color: L.INK}}}},
  sections: [{
    properties: {page: {margin: {top: 1200, right: 1440, bottom: 1200, left: 1440}}},
    headers: {default: new Header({children: [new Paragraph({
      alignment: AlignmentType.RIGHT, spacing: {after: 0},
      children: [new TextRun({text: 'Distributed Taxi Trip Analytics — Hadoop, HDFS and Python MapReduce',
                              size: 16, color: L.MUTED, font: 'Calibri'})]})]})},
    footers: {default: new Footer({children: [new Paragraph({
      alignment: AlignmentType.CENTER, spacing: {before: 0},
      children: [new TextRun({children: ['Page ', PageNumber.CURRENT, ' of ', PageNumber.TOTAL_PAGES],
                              size: 16, color: L.MUTED, font: 'Calibri'})]})]})},
    children: [...title, ...toc, ...s1, ...s2, ...s3, ...s4, ...s5, ...s6,
               ...s7, ...s8, ...s9, ...s10, ...s11, ...s12,
               ...s13, ...s14, ...s15, ...s16]
  }]
});

Packer.toBuffer(doc).then(buf => {
  const out = path.join(B, 'docs', 'Big_Data_Hadoop_Taxi_Analytics_Report.docx');
  fs.writeFileSync(out, buf);
  console.log('wrote', out, (buf.length / 1024).toFixed(0) + ' KB');
});
